# fly.toml app configuration file generated for dominion-deck-dev on 2026-05-28T13:32:00+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dominion-deck-dev'
primary_region = 'cdg'

[build]

[env]
  BACKEND_URL = "http://dominion-deck-api-dev.internal:8000"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
